name: Update badges

on:
  schedule:
    # Runs at 2am UTC
    - cron: "0 2 * * *"

jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: NKameswar/badges-readme@main
        with:
          CREDLY_USER: <nedunuri-satya-sai-prabhakara-kameswar> # optional, but default will use the same from GitHub
